import type { LucideIcon } from 'lucide-react';
import {
  AlertTriangle,
  ArrowDown,
  ArrowUp,
  Ban,
  Bell,
  CalendarClock,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Circle,
  CircleDashed,
  ClipboardList,
  Clock,
  Download,
  FileText,
  Flame,
  GraduationCap,
  LayoutDashboard,
  Loader2,
  LogOut,
  Menu,
  Minus,
  Moon,
  Package,
  Plus,
  RadioTower,
  ScrollText,
  Search,
  Settings,
  ShieldAlert,
  Siren,
  Sun,
  Truck,
  Users,
  Wrench,
  X,
} from 'lucide-react';
import type { StatusRole } from '@boxalarm/design-tokens';

export {
  AlertTriangle,
  ArrowDown,
  ArrowUp,
  Ban,
  Bell,
  CalendarClock,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Circle,
  CircleDashed,
  ClipboardList,
  Clock,
  Download,
  FileText,
  Flame,
  GraduationCap,
  LayoutDashboard,
  Loader2,
  LogOut,
  Menu,
  Minus,
  Moon,
  Package,
  Plus,
  RadioTower,
  ScrollText,
  Search,
  Settings,
  ShieldAlert,
  Siren,
  Sun,
  Truck,
  Users,
  Wrench,
  X,
};
export type { LucideIcon };

/** Status glyph + word, one entry per status role token (docs/design.md §2.3). Colour is never
 * the only carrier — every StatusChip renders the icon and the word alongside the hue. */
export const STATUS_ICON: Record<StatusRole, LucideIcon> = {
  ok: CheckCircle2,
  warning: Clock,
  caution: AlertTriangle,
  danger: Ban,
  info: ArrowUp,
  neutral: Circle,
};

export const STATUS_WORD: Record<StatusRole, string> = {
  ok: 'OK',
  warning: 'Due soon',
  caution: 'Caution',
  danger: 'Alarm',
  info: 'Queued',
  neutral: 'N/A',
};
